# -*- coding: utf-8 -*-
"""arithmetic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BGfLCwdfApFgEiwyH0V6MocH2pEpB1rX
"""

def add(x,y):
  return x + y
def minus(x,y):
  return x - y
def multi(x,y):
  return x * y
def divide(x, y):
  try:
    return x / y
  except:
    print("다시 입력해주세요")

if __name__ == '__main__':
  print(add(1,2))
  print(minus(1,2))
  print(multi(1,2))
  divide(1,0)

