# -*- coding: utf-8 -*-
"""string_util.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVkUB_pjgb81R7pkWA_lUGt6Ath0QWY4
"""

def reverse_string(text):
  return text[::-1]
def count_word(text):
  return len(text.split(" "))

if __name__ == '__main__':
  text = "i love you"
  print(reverse_string(text))
  print(count_word(text))

